/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ReciclarControlador;
import Entidades.Reciclar;
import Entidades.Vidrio;
import java.util.Iterator;

/**
 *
 * @author Antonella
 */
public class TipoVidrio extends javax.swing.JFrame {

    /**
     * Creates new form TipoVidrio
     */
    ReciclarControlador rec = new ReciclarControlador();
    
    public TipoVidrio() {
        initComponents();
        titulo();
    }
    
    public void titulo(){
         for(Iterator<String> it= Vidrio.getTipo_vidrio().listIterator();it.hasNext();){
             lbl_domestico.setText(it.next());
             lbl_industrial.setText(it.next());
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Domestico = new javax.swing.JButton();
        btn_Industrial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_domestico = new javax.swing.JLabel();
        lbl_industrial = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(440, 312));
        setMinimumSize(new java.awt.Dimension(440, 312));
        setSize(new java.awt.Dimension(440, 312));
        getContentPane().setLayout(null);

        btn_Domestico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vidrioDo.PNG"))); // NOI18N
        btn_Domestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DomesticoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Domestico);
        btn_Domestico.setBounds(40, 80, 160, 150);

        btn_Industrial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vidrioInd.PNG"))); // NOI18N
        btn_Industrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IndustrialActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Industrial);
        btn_Industrial.setBounds(230, 80, 160, 150);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Selecciona el tipo de Vidrio");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 20, 190, 50);

        lbl_domestico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_domestico.setText("Domes");
        getContentPane().add(lbl_domestico);
        lbl_domestico.setBounds(100, 240, 80, 14);

        lbl_industrial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_industrial.setText("Indus");
        getContentPane().add(lbl_industrial);
        lbl_industrial.setBounds(280, 240, 60, 14);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tipovidrio.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-150, -290, 590, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DomesticoActionPerformed
        int id=21;
        Reciclar re = new Reciclar(id, 1);
        
        rec.agregarDes(re, "brahianf@unicauca.edu.co");
        System.out.println("VIDRIO DOMESTICO");
    }//GEN-LAST:event_btn_DomesticoActionPerformed

    private void btn_IndustrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IndustrialActionPerformed
        int id=22;
        Reciclar re = new Reciclar(id, 1);
        
        rec.agregarDes(re, "brahianf@unicauca.edu.co");
        System.out.println("VIDRIO INDUSTRIAL");
    }//GEN-LAST:event_btn_IndustrialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoVidrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoVidrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoVidrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoVidrio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoVidrio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Domestico;
    private javax.swing.JButton btn_Industrial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_domestico;
    private javax.swing.JLabel lbl_industrial;
    // End of variables declaration//GEN-END:variables
}
