/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Papel;
import java.util.Iterator;

/**
 *
 * @author Antonella
 */
public class TipoPapel extends javax.swing.JFrame {

    /**
     * Creates new form TipoPapel
     */
    public TipoPapel() {
        initComponents();
        titulo();
    }
    
    public void titulo(){
         for(Iterator<String> it= Papel.getTipo_papel().listIterator();it.hasNext();){
             lbl_periodico.setText(it.next());
             lbl_carton.setText(it.next());
             lbl_cartulina.setText(it.next());
             lbl_revista.setText(it.next());
             lbl_otro.setText(it.next());
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_periodico = new javax.swing.JLabel();
        lbl_carton = new javax.swing.JLabel();
        lbl_cartulina = new javax.swing.JLabel();
        lbl_revista = new javax.swing.JLabel();
        lbl_otro = new javax.swing.JLabel();
        btn_periodico = new javax.swing.JButton();
        btn_carton = new javax.swing.JButton();
        btn_cartulina = new javax.swing.JButton();
        btn_revista = new javax.swing.JButton();
        btn_otro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(565, 490));
        setMinimumSize(new java.awt.Dimension(565, 490));
        setPreferredSize(new java.awt.Dimension(565, 490));
        setSize(new java.awt.Dimension(565, 490));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Selecciona el tipo de Papel");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 20, 230, 40);

        lbl_periodico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_periodico.setText("jLabel2");
        getContentPane().add(lbl_periodico);
        lbl_periodico.setBounds(70, 230, 70, 20);

        lbl_carton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_carton.setText("jLabel3");
        getContentPane().add(lbl_carton);
        lbl_carton.setBounds(244, 230, 50, 20);

        lbl_cartulina.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_cartulina.setText("jLabel4");
        getContentPane().add(lbl_cartulina);
        lbl_cartulina.setBounds(420, 230, 60, 20);

        lbl_revista.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_revista.setText("jLabel5");
        getContentPane().add(lbl_revista);
        lbl_revista.setBounds(164, 420, 50, 14);

        lbl_otro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_otro.setText("jLabel6");
        getContentPane().add(lbl_otro);
        lbl_otro.setBounds(324, 420, 60, 14);

        btn_periodico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/periodico.JPG"))); // NOI18N
        btn_periodico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_periodicoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_periodico);
        btn_periodico.setBounds(40, 80, 134, 146);

        btn_carton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carton.JPG"))); // NOI18N
        btn_carton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cartonActionPerformed(evt);
            }
        });
        getContentPane().add(btn_carton);
        btn_carton.setBounds(200, 100, 150, 120);

        btn_cartulina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cartulina.JPG"))); // NOI18N
        btn_cartulina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cartulinaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cartulina);
        btn_cartulina.setBounds(380, 90, 140, 130);

        btn_revista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/revista.JPG"))); // NOI18N
        btn_revista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_revistaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_revista);
        btn_revista.setBounds(110, 270, 160, 140);

        btn_otro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/otro.PNG"))); // NOI18N
        btn_otro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_otroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_otro);
        btn_otro.setBounds(300, 280, 120, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PAPEL ARRUGADO.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 550, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_periodicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_periodicoActionPerformed
        // TODO add your handling code here:
        System.out.println("PAPEL PERIODICO");
    }//GEN-LAST:event_btn_periodicoActionPerformed

    private void btn_otroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_otroActionPerformed
        // TODO add your handling code here:
        System.out.println("OTRO");
    }//GEN-LAST:event_btn_otroActionPerformed

    private void btn_revistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_revistaActionPerformed
        // TODO add your handling code here:
        System.out.println("PAPEL DE REVISTA");
    }//GEN-LAST:event_btn_revistaActionPerformed

    private void btn_cartulinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cartulinaActionPerformed
        // TODO add your handling code here:
        System.out.println("CARTULINA");
    }//GEN-LAST:event_btn_cartulinaActionPerformed

    private void btn_cartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cartonActionPerformed
        // TODO add your handling code here:
        System.out.println("CARTÓN");
    }//GEN-LAST:event_btn_cartonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoPapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoPapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoPapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoPapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoPapel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_carton;
    private javax.swing.JButton btn_cartulina;
    private javax.swing.JButton btn_otro;
    private javax.swing.JButton btn_periodico;
    private javax.swing.JButton btn_revista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_carton;
    private javax.swing.JLabel lbl_cartulina;
    private javax.swing.JLabel lbl_otro;
    private javax.swing.JLabel lbl_periodico;
    private javax.swing.JLabel lbl_revista;
    // End of variables declaration//GEN-END:variables
}
