/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Control.Organico;
import Control.Papel;
import Control.Plastico;
import Control.Vidrio;
import java.util.Iterator;

/**
 *
 * @author Antonella
 */
public class Tipo extends javax.swing.JFrame {
    
    public Tipo() {
        initComponents();
        Tipo();
    }
       
    public static int sel=0;

    public static void setSel(int sel) {
        Tipo.sel = sel;
    }
    
    public void Tipo(){
        
        if(sel==0){
            lbl_tipo.setText("Papel");
             for(Iterator<String> it= Papel.getTipo_papel().listIterator();it.hasNext();){
                String tipo=it.next();
                cbx_tipo.addItem(tipo);
             }
        }else{
            if(sel==1){
                lbl_tipo.setText("Vidrio");
                for(Iterator<String> it= Vidrio.getTipo_vidrio().listIterator();it.hasNext();){
                    String tipo=it.next();
                    cbx_tipo.addItem(tipo);
                }
            }else{
                if(sel==2){
                    lbl_tipo.setText("Organico");
                    for(Iterator<String> it= Organico.getTipo_organico().listIterator();it.hasNext();){
                        String tipo=it.next();
                        cbx_tipo.addItem(tipo);
                    }
                }else{
                    if(sel==3){
                        lbl_tipo.setText("Plastico");
                        for(Iterator<String> it= Plastico.getTipo_plastico().listIterator();it.hasNext();){
                            String tipo=it.next();
                            cbx_tipo.addItem(tipo);
                        }
                    }       
                }
            }  
        }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tipo = new javax.swing.JLabel();
        cbx_tipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(565, 330));
        setMinimumSize(new java.awt.Dimension(565, 330));
        setPreferredSize(new java.awt.Dimension(565, 330));
        setSize(new java.awt.Dimension(565, 330));
        getContentPane().setLayout(null);

        lbl_tipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_tipo.setForeground(new java.awt.Color(51, 153, 0));
        lbl_tipo.setText("Tipo");
        getContentPane().add(lbl_tipo);
        lbl_tipo.setBounds(300, 120, 60, 17);

        cbx_tipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbx_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_tipoActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_tipo);
        cbx_tipo.setBounds(370, 120, 170, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Selecciona el tipo de residuo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 50, 210, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tipo.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-20, 0, 570, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_tipoActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_cbx_tipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx_tipo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_tipo;
    // End of variables declaration//GEN-END:variables
}
