/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Plastico;
import java.util.Iterator;

/**
 *
 * @author Antonella
 */
public class TipoPlastico extends javax.swing.JFrame {

    /**
     * Creates new form TipoPlastico
     */
    public TipoPlastico() {
        initComponents();
        nombre();
    }

    public void nombre(){
         for(Iterator<String> it= Plastico.getTipo_plastico().listIterator();it.hasNext();){
             lbl_1.setText(it.next());
             lbl_2.setText(it.next());
             lbl_3.setText(it.next());
             lbl_4.setText(it.next());
             lbl_5.setText(it.next());
         }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_1 = new javax.swing.JLabel();
        lbl_2 = new javax.swing.JLabel();
        lbl_3 = new javax.swing.JLabel();
        lbl_4 = new javax.swing.JLabel();
        lbl_5 = new javax.swing.JLabel();
        btn_botella = new javax.swing.JButton();
        btn_bolsa = new javax.swing.JButton();
        btn_pitillo = new javax.swing.JButton();
        btn_desechable = new javax.swing.JButton();
        btn_otro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Selecciona el tipo de Plastico");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 250, 40);

        lbl_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_1.setText("jLabel2");
        getContentPane().add(lbl_1);
        lbl_1.setBounds(90, 210, 60, 15);

        lbl_2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_2.setText("v");
        getContentPane().add(lbl_2);
        lbl_2.setBounds(220, 210, 70, 15);

        lbl_3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_3.setText("jLabel4");
        getContentPane().add(lbl_3);
        lbl_3.setBounds(390, 210, 70, 15);

        lbl_4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_4.setText("jLabel5");
        getContentPane().add(lbl_4);
        lbl_4.setBounds(124, 380, 70, 15);

        lbl_5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_5.setText("jLabel6");
        getContentPane().add(lbl_5);
        lbl_5.setBounds(300, 380, 70, 15);

        btn_botella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botellas.PNG"))); // NOI18N
        getContentPane().add(btn_botella);
        btn_botella.setBounds(60, 90, 100, 110);

        btn_bolsa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bolsa.PNG"))); // NOI18N
        getContentPane().add(btn_bolsa);
        btn_bolsa.setBounds(200, 80, 120, 120);

        btn_pitillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pitillo.PNG"))); // NOI18N
        getContentPane().add(btn_pitillo);
        btn_pitillo.setBounds(350, 80, 130, 120);

        btn_desechable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/desechables.PNG"))); // NOI18N
        btn_desechable.setText("\n\n");
        getContentPane().add(btn_desechable);
        btn_desechable.setBounds(90, 250, 140, 120);

        btn_otro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/otro.PNG"))); // NOI18N
        getContentPane().add(btn_otro);
        btn_otro.setBounds(270, 250, 130, 130);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tipoPlas.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-100, 0, 630, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoPlastico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoPlastico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoPlastico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoPlastico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoPlastico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bolsa;
    private javax.swing.JButton btn_botella;
    private javax.swing.JButton btn_desechable;
    private javax.swing.JButton btn_otro;
    private javax.swing.JButton btn_pitillo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    private javax.swing.JLabel lbl_4;
    private javax.swing.JLabel lbl_5;
    // End of variables declaration//GEN-END:variables
}
