/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Organico;
import java.util.Iterator;

/**
 *
 * @author Antonella
 */
public class TipoOrganico extends javax.swing.JFrame {

    /**
     * Creates new form TipoOrganico
     */
    public TipoOrganico() {
        initComponents();
    }

    public void nombre(){
         for(Iterator<String> it= Organico.getTipo_organico().listIterator();it.hasNext();){
             lbl_fruta.setText(it.next());
             lbl_pan.setText(it.next());
             lbl_comida.setText(it.next());
             lbl_huevo.setText(it.next());
             lbl_verduras.setText(it.next());
             lbl_otro.setText(it.next());
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_fruta = new javax.swing.JLabel();
        lbl_pan = new javax.swing.JLabel();
        lbl_comida = new javax.swing.JLabel();
        lbl_huevo = new javax.swing.JLabel();
        lbl_verduras = new javax.swing.JLabel();
        lbl_otro = new javax.swing.JLabel();
        btn_fruta = new javax.swing.JButton();
        btn_pan = new javax.swing.JButton();
        btn_comida = new javax.swing.JButton();
        btn_huevo = new javax.swing.JButton();
        btn_verduras = new javax.swing.JButton();
        btn_otro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 480));
        setMinimumSize(new java.awt.Dimension(550, 480));
        setPreferredSize(new java.awt.Dimension(550, 480));
        setSize(new java.awt.Dimension(550, 480));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Selecciona el tipo de residuo organico");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 10, 320, 40);

        lbl_fruta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_fruta.setText("jLabel2");
        getContentPane().add(lbl_fruta);
        lbl_fruta.setBounds(50, 210, 70, 20);

        lbl_pan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_pan.setText("jLabel3");
        getContentPane().add(lbl_pan);
        lbl_pan.setBounds(250, 210, 50, 14);

        lbl_comida.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_comida.setText("jLabel4");
        getContentPane().add(lbl_comida);
        lbl_comida.setBounds(380, 210, 80, 14);

        lbl_huevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_huevo.setText("jLabel5");
        getContentPane().add(lbl_huevo);
        lbl_huevo.setBounds(50, 380, 60, 20);

        lbl_verduras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_verduras.setText("jLabel6");
        getContentPane().add(lbl_verduras);
        lbl_verduras.setBounds(210, 400, 80, 20);

        lbl_otro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_otro.setText("jLabel7");
        getContentPane().add(lbl_otro);
        lbl_otro.setBounds(410, 390, 50, 20);

        btn_fruta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fruta.JPG"))); // NOI18N
        getContentPane().add(btn_fruta);
        btn_fruta.setBounds(40, 90, 127, 110);

        btn_pan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pan.JPG"))); // NOI18N
        getContentPane().add(btn_pan);
        btn_pan.setBounds(210, 80, 120, 120);

        btn_comida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comida.JPG"))); // NOI18N
        getContentPane().add(btn_comida);
        btn_comida.setBounds(370, 90, 120, 110);

        btn_huevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/huevo.JPG"))); // NOI18N
        getContentPane().add(btn_huevo);
        btn_huevo.setBounds(40, 260, 110, 110);

        btn_verduras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verduras.JPG"))); // NOI18N
        getContentPane().add(btn_verduras);
        btn_verduras.setBounds(200, 250, 140, 140);

        btn_otro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/otro.PNG"))); // NOI18N
        getContentPane().add(btn_otro);
        btn_otro.setBounds(370, 250, 120, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tipoOrganico.jpg"))); // NOI18N
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 540, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoOrganico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoOrganico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoOrganico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoOrganico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoOrganico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_comida;
    private javax.swing.JButton btn_fruta;
    private javax.swing.JButton btn_huevo;
    private javax.swing.JButton btn_otro;
    private javax.swing.JButton btn_pan;
    private javax.swing.JButton btn_verduras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_comida;
    private javax.swing.JLabel lbl_fruta;
    private javax.swing.JLabel lbl_huevo;
    private javax.swing.JLabel lbl_otro;
    private javax.swing.JLabel lbl_pan;
    private javax.swing.JLabel lbl_verduras;
    // End of variables declaration//GEN-END:variables
}
